### ISSUE TITLE
Export all asciicasts available in my profile

### ISSUE THREAD

**Issue by mosbth** [asciinema/asciinema.org#186]
I saw that #159 was closed so I'll ask a related issue, but a bit more specific.

I have almost 100 asciicasts on my account. I use them in my own website for educational purpose. So I have "invested" in this service. I'm not really interested in setting up my own server, I'm rather happy with the excellent service as it is.

But, to avoid disaster I would like to get a backup of all my asiicasts, I would like to export all my asciicasts I have uploaded to asciinema.org. This is just in case something happens, like asciinema.org gets sold, license is changed and original website gets closed down and I loose all my asciicasts and my own site gets broken until I record it all again...

Can it be done today - exporting all uploaded asiicasts - easy or hard way? Could it be integrated into the website? And/Or could the commandline utility automatically save a copy of any uploaded asciicast (this is really a question for the recorder repo - I'll ask it there depending on the answer I get here).

**Comment by sickill** [comment]
First, I don't have a plan to sell it, neither to change the license nor shut it down. It's **not a product**, and I don't plan to turn it into business (because it would make it more serious and less fun, and fun is more precious than money).

But nobody knows the future and I fully understand your concern. Independence of asciicasts from asciinema.org service was something that was discussed by several people. Actually, if I was in your position (having "invested" this much in the service) I'd be equally concerned about it.

Because it's not a product/business I don't have a reason to create "vendor lock-in". That's why my focus now is on decoupling the recordings from the service and allowing people to self-host them in an easy way. asciinema.org is of course going to stay for those who don't want to self-host (most?).

First part of the process of decoupling was creating an official [asciicast format](https://github.com/asciinema/asciinema/blob/master/doc/asciicast-v1.md) and allowing [recording to local files](https://github.com/asciinema/asciinema/pull/80) (also see [1.0 annoucement](http://blog.asciinema.org/post/one-point-o/)). Next part is to update the JS player so it's able to consume asciicasts directly without a need for pre-processing step, which is currently required, and done by asciinema.org. Once that's done you'll be able to embed asciicasts on your pages by downloading player (1 JS file + 1 CSS file + optionally a theme CSS file) and the actual asciicast file, and adding them to your HTML. The other self-hosting option I plan to add is ability to run your own "mini asciinema.org" site with `asciinema server /path/to/your/asciicasts -p 8080`, and embed asciicasts in your pages directly from there (yourdomain:8080).

Re exporting: It's not trivial but possible to export the asciicasts now, so if you can't wait for the described work to be finished I can give you a list of manual steps for exporting. Anyway, this topic is my focus for the following couple of months. I hope this makes you more comfortable.

**Comment by mosbth** [comment]
Yep, makes me comfortable. Seems like you have it all under control. I will sit tight and continue investing. I like the plan you present above.

**Comment by AVGP** [comment]
@sickill High five for this!
Looking forward to 1.0 then :-)

**Comment by sickill** [comment]
@AVGP 1.0 is already [out there](http://blog.asciinema.org/post/one-point-o/). The plan described is for 1.1 or 1.2.

**Comment by AVGP** [comment]
Hah, okay, I'm an idiot, sorry! Soooo, I'm looking forward to exporting / locally recording asciicasts soon, then ^^
