### ISSUE TITLE
Make mp4 from recorded

### ISSUE THREAD

**Issue by fthamura** [asciinema/asciinema.org#189]
hi all

I want to make recorded text become video tutorial for my recorded asciinema

so we can play locally (we work locally mostly) and may be to you tube.
any idea?

**Comment by sickill** [comment]
asciinema solves the problem of recording terminal specifically by avoiding heavy video files/codecs etc. There's no plan to add conversion to mp4 in a foreseeable future, sorry.

**Comment by rjb25** [comment]
For now what anyone who wants an mp4 can do is use an [ascciicast to gif converter](https://github.com/tav/asciinema2gif) then use a [gif to mp4 converter](http://gif-2-mp4.com/) or [this](http://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line). Why do this instead of just using a recorder that goes to mp4 in the first place? Well asciicasts json format is editable so you can take out information or edit information. Most terminal to mp4 converters do not have this? Why not just use the embedded media player? Because that relies on asciinema.org being there forever. But you can make your own asciinema hosting website! Well not all of us feel like setting up our own website. Why do we want mp4 instead of gif? because there is no real good solution for a gif player that can be rewinded/paused.

**Comment by sebastian-philipp** [comment]
Another idea would be to use a tool like peek to make a screen recording of the output

**Comment by frankclaassens** [comment]
> For now what anyone who wants an mp4 can do is use an [ascciicast to gif converter](https://github.com/tav/asciinema2gif) then use a [gif to mp4 converter](http://gif-2-mp4.com/) or [this](http://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line). Why do this instead of just using a recorder that goes to mp4 in the first place? Well asciicasts json format is editable so you can take out information or edit information. However you should not need an mp4 as you can use the embedded media.

Can you give me an example of how to use embedded media to send a recording on whatsapp without it having to open the mobile browser when clicking on the link?

**Comment by ixe013** [comment]
Another option for making a gif without publishing to asciinema.org is to do `asciinema play zzz.cast` under a [LiceCap window](https://www.cockos.com/licecap/) (Windows and Mac only though)

**Comment by rpaciorek** [comment]
I created Python (based on pyte and moviepy) converter for ascciicast (v2) to video (mp4 file): https://github.com/opcode-eu-org-libs/asciicast2movie

It can be used also as module to generate moviepy video clip, that can be used as part of other video file.

**Comment by yangyang5214** [comment]
Share a way.  😊

```
docker pull beer5215/asciicast2mp4
docker run --rm -v $PWD:/data beer5215/asciicast2mp4 xxx.cast

cd playlog/xxx 

$ ls
0.png  10.png  11.png  12.png  1.png  2.png  3.png  4.png  5.png  6.png  7.png  8.png  9.png  result.mp4  result.time  tmp.time

open result.mp4
```

**Comment by qaqland** [comment]
In many cases, such as an environment without a graphics card or incomplete wayland desktop, it is very inconvenient to record video directly. So it would be helpful to have mp4 format.

**Comment by xiaohanyu** [comment]
Hey guys,

For anyone who needs to convert an existing `*.cast` file to mp4, I wrote a Node.js CLI tool for this:

- GitHub: https://github.com/xiaohanyu/asciinema2video/
- Npm: https://www.npmjs.com/package/asciinema2video
- Live demo: https://asciinema.org/a/762502

@fthamura @qaqland @tronicum
