### ISSUE TITLE
getting width and height of an asciinema

### ISSUE THREAD

**Issue by jbenet** [asciinema/asciinema.org#234]
in https://github.com/jbenet/asciinema-selfhost/ i used to get the size with: https://github.com/jbenet/asciinema-selfhost/blob/f2f2bd8fed21b42ee59d5e7b46b5fd09f0285b1e/index.js#L60-L61 which was pretty terrible but seemed to work always.

I'm updating it. Now, using the new `.json` url (eg https://asciinema.org/a/91304.json) some asciinema json files have the `width/height` attributes, and some do not (eg https://asciinema.org/a/103367.json) (these were grabbed as examples randomly from public listing). Maybe all old versions of files need to be updated? Or if not, is there a better (robust) way to get the width/height always? Thanks!

**Comment by sickill** [comment]
The JSON files without width/height are produced by old (< 1.0.0) version of the player. asciinema.org still supports these clients but I plan to drop the support soon (these clients are 2-3 years old now).

You can do the following. Check what's the first character in the file.

If it's `{` - parse with JSON.parse and get `width` and `height` properties.

If it's `[` - it's more tricky because it's a legacy format :) First parse with JSON.parse (and assign it to let's say `data` var), then get `data[0][1]["lines"]`. The result will be an object with line numbers as keys (count the keys to get the `height`). To get the `width`... First get first line (`data[0][1]["lines"]["0"]`), then extract all strings from it (the line is an array of 2-element arrays where strings are first element), concatenate them and the length of the string will be `width` of the terminal :) Alternatively you can just not support this old format.

**Comment by jbenet** [comment]
thanks!
